#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/node_modules/pink/bin/pink.js" "$@"
  ret=$?
else 
  node  "$basedir/node_modules/pink/bin/pink.js" "$@"
  ret=$?
fi
exit $ret

$ C:\Users\Pili\AppData\Roaming\npm\pink run slides.js